[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/"
status = 200

[[redirects]]
from = "/*"
to = "/"
status = 200

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

# [build]
# command = "npm run build"
# publish = "build"
# functions = "netlify/functions"
